name: farmers_friend
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter:
  queries:
  flutter_flux:
  rxdart:
  camera:
  tflite:
  flip_panel:
  flutter_speed_dial:
  charts_flutter:
  flutter_swiper:
  flutter_spinkit:
  webview_flutter:
  cached_network_image:
  http:
  sqflite:
  bubble:
  path_provider:
  test:
  flutter_sound:
  intl:
  flutter_local_notifications:
  photo_view:
  flutter_launcher_icons:
  fluttertoast:
  flushbar:
  shared_preferences:
  logger:
  carousel_slider:
  image_picker:
  youtube_player:
  youtube_player_flutter:
  card_selector:
  percent_indicator:
  scoped_model:
  video_player:
  after_layout:
  rflutter_alert:
  flutter_cupertino_date_picker:
  flutter_screenutil:
  autocomplete_textfield:
  speech_recognition:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/omni_ai.png"
  adaptive_icon_background: "#ffffff"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/tomatoes.png
    - assets/images/camera_screen_bg.png
    - assets/images/maize.png
    - assets/images/pests.png
    - assets/cornGermination.mp4
    - assets/images/omni_ai_logo.png
    - assets/images/omni_ai.png
    - assets/plant_disease_model.tflite
    - assets/crop_labels.txt
    - assets/images/crops.png
    - assets/images/graph.png
    - assets/images/locust.jpg
    - assets/images/grain_borer.jpg
    - assets/images/stem_borer.jpg
    - assets/images/fall_army_worm.jpg
    - assets/images/maize.jpg
    - assets/images/in.png
    - assets/images/flag_ghana.png
    - assets/images/crops.png
    - assets/images/maize_farm.jpg
    - assets/images/rice_banner_1.jpg
    - assets/images/rice.jpg
    - assets/images/payment.png
    - assets/images/chat.png
    - assets/images/gallery_option.png
    - assets/images/camera_option.png
    - assets/images/sun.png
    - assets/images/thunderstorm.png
    - assets/images/sunshine.png
    - assets/images/carrot_t.jpg
    - assets/images/cabbage_t.jpg
    - assets/images/tomato_t.png
    - assets/images/garden_eggs_t.jpg
    - assets/images/cauliflower_t.jpg
    - assets/images/analysis.png
    - assets/images/clouds.png
    - assets/images/forcast_bg.png
    - assets/images/limitless_ai.png
    - assets/images/alert.png
    - assets/images/yellow_cloud.png
    - assets/images/raindrop.png
    - assets/images/heavyrain.png
    - assets/images/bot.png
    - assets/images/bot_full.png
    - assets/images/parisback.png
    - assets/images/dotEmpty.png
    - assets/images/0.png
    - assets/images/30.png
    - assets/images/32.png
    - assets/images/26.png
    - assets/images/28.png
    - assets/images/dotBlueishFull.png
    - assets/images/plant.png
    - assets/images/plant_s.png
    - assets/images/money.png
    - assets/images/money_s.png
    - assets/images/camera.png
    - assets/images/camera_s.png
    - assets/images/analytics.png
    - assets/images/analytics_s.png
    - assets/images/file.png
    - assets/images/file_s.png
    - assets/images/help.png
    - assets/images/help_s.png
    - assets/images/d1s.png
    - assets/images/d2s.png
    - assets/images/d3s.png
    - assets/images/d4s.png
    - assets/images/d5s.png
    - assets/images/d6s.png
    - assets/images/d7s.png
    - assets/images/d8s.png
    - assets/images/d9s.png
    - assets/images/n1s.png
    - assets/images/n2s.png
    - assets/images/wind.png
    - assets/images/pres.png
    - assets/images/water.png



  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-SemiBold.ttf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
